export * from './createDefunct'
export * from './getDefuncts'
export * from './getDefunctsByUser'
export * from './searchDefunctName'
export * from './updateDefunct'
export * from './deleteDefunct'
export * from './uploadDocImages'